config/routes.rb
Rails.application.routes.draw do
  resources :vocations
  resources :works
  resources :supplies
  resources :users
  root 'static_pages#home'
  get '/home' => 'static_pages#home'
  get '/building' => 'static_pages#building'
  get '/projects' => 'static_pages#projects'
  get '/geo' => 'static_pages#geo'
  get '/about' => 'static_pages#about'
  get '/contacts' => 'static_pages#contacts'
  get '/hh' => 'static_pages#hh'
  get '/work' => 'static_pages#work'
  get '/supply' => 'static_pages#supply'
  resources :projects
  resources :sros

  namespace :admin do
    resources :projects
    resources :sros
    resources :vocations
    resources :works
    resources :supplies
    resources :users
    root 'projects#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  include Paperclip::Glue

  has_attached_file :photo, styles: { big: "1200x500>", medium: "1000x657>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  validates :photo, attachment_presence: true
  validates :title, :text, presence: true
end

app/models/sro.rb
class Sro < ApplicationRecord
  include Paperclip::Glue

  has_attached_file :photo, styles: { big: "1200x500>", medium: "1000x657>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  validates :photo, attachment_presence: true
end

app/models/supply.rb
class Supply < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/vocation.rb
class Vocation < ApplicationRecord
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @projects = Project.all
    @sros = Sro.all
  end
  def projects
    @projects = Project.all
  end
  def hh
    @vocations = Vocation.all
  end
  def work
    @works = Work.all
  end
  def supply
    @supplies = Supply.all
  end
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_action :set_supply, only: [:show, :edit, :update, :destroy]

  # GET /supplies
  # GET /supplies.json
  def index
    @supplies = Supply.all
  end

  # GET /supplies/1
  # GET /supplies/1.json
  def show
  end

  # GET /supplies/new
  def new
    @supply = Supply.new
  end

  # GET /supplies/1/edit
  def edit
  end

  # POST /supplies
  # POST /supplies.json
  def create
    @supply = Supply.new(supply_params)

    respond_to do |format|
      if @supply.save
        format.html { redirect_to @supply, notice: 'Supply was successfully created.' }
        format.json { render :show, status: :created, location: @supply }
      else
        format.html { render :new }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplies/1
  # PATCH/PUT /supplies/1.json
  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to @supply, notice: 'Supply was successfully updated.' }
        format.json { render :show, status: :ok, location: @supply }
      else
        format.html { render :edit }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplies/1
  # DELETE /supplies/1.json
  def destroy
    @supply.destroy
    respond_to do |format|
      format.html { redirect_to supplies_url, notice: 'Supply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply
      @supply = Supply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supply_params
      params.fetch(:supply, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        # Сказать UserMailer отослать приветственное письмо после сохранения
        UserMailer.with(user: @user).welcome_email.deliver_later
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
end

app/controllers/vocations_controller.rb
class VocationsController < ApplicationController
  before_action :set_vocation, only: [:show]

  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vocation
      @vocation = Vocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vocation_params
      params.fetch(:vocation, {})
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.fetch(:work, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vocations_helper.rb
module VocationsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admin/hh/edit.html.erb
<%= form_for [:admin, @sro], html: { multipart: true } do |form| %>
  <div class="form-group">
    <%= form.label :title %>
  </div>
  <%= form.text_area :text %>
  <%= form.file_field :photo %>
  <%= form.submit 'Сохранить', class: 'btn btn-default'%>
<% end %>

app/views/admin/hh/index.html.erb
<%= link_to 'Создать', new_admin_sro_path, class: 'btn btn-default' %>

<table class="table">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Text</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @sros.each do |sro| %>
      <tr>
        <td>
          <%= image_tag sro.photo.url(:small) %>
        </td>
        <td>
          <%= sro.text %>
        </td>
        <td>
          <%= link_to 'Редактировать', edit_admin_sro_path(sro), class: 'btn btn-default' %></td>
        </td>
        <td>
          <%= link_to 'Удалить', admin_sro_path(sro), class: 'btn btn-default',
          method: :delete,
          data: { confirm: 'Продолжить?' } %>
        </td>
    </tr>

    <% end %>
  </tbody>

app/views/admin/hh/new.html.erb
<%= form_for [:admin, @sro], html: { multipart: true } do |form| %>
  <div class="form-group">
    <%= form.label :title %>
  </div>
  <%= form.text_area :text %>
  <%= form.file_field :photo %>
  <%= form.submit 'Создать', class: 'btn btn-default'%>
<% end %>

app/views/admin/hh/show.html.erb
<%= image_tag @sro.photo.url %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NORD PLAN</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Петровский фарватер (Настройки)</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li>
                <%= active_link_to 'На сайт', root_path, active: :exact, wrap_tag: :li %>
              </li>
              <li>
                <%= active_link_to 'Объекты', admin_projects_path, wrap_tag: :li %>
              </li>
              <li>
                <%= active_link_to 'СРО', admin_sros_path, wrap_tag: :li %>
              </li>
              <li>
                <%= active_link_to 'Вакансии', admin_vocations_path, wrap_tag: :li %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/partials/_footer.html.erb
<footer class="footer navbar-bottom">
      <div class="container-fluid">
        <p class="text-muted">
          <br>191036, Санкт-Петербург, Невский пр., д.111/3,лит. А., пом.  61 Н
          <br>ИНН/КПП: 7841321703 / 784201001
          <br>тел/факс (812) 309-32-09
          <br>e-mail: mail@petrfarv.ru</p>
          <br>
      </div>
</footer>

app/views/layouts/partials/_header.html.erb
<div class="navbar-wrapper">

  <div class="container">
    <nav class="navbar navbar-inverse navbar-fixed-top">

      <div class="container">
        <div class="tel hidden-xs">
        <a href="tel:+78123093209">8(812)3093209</a>
        <br>
        <a href="mailto:mail@petrfarv.ru?subject=feedback">mail@petrfarv.ru</a></p>

        </div>
        <div class="row">
          <div class="col-sm-6">
            <a href="/home">
            <%= image_tag(image_path('logo.png'), alt: 'nordplan', class: 'logo hidden-xs') %>
            <%= image_tag(image_path('petr.png'), alt: 'nordplan', class: 'logo-2 hidden-xs') %></a>
          </div>
          <div class="col-sm-6">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="visible-xs navbar-brand" href="/home">
              <%= image_tag(image_path('petr.png'), alt: 'nordplan', class: 'logo-3') %></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
<!--            <li><%= active_link_to 'Главная', '/home'%></li> -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">О компании<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= active_link_to 'История создания', '/about'%></li>
                <li><%= active_link_to 'Вакансии', '/hh'%></li>
              </ul>
          <!--     <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Деятельность <span class="caret"></span></a>
           <ul class="dropdown-menu">
                <li><%= active_link_to 'Изыскания', '/geo'%></li>
                <li><%= active_link_to 'Строительство', '/building'%></li>
                <li><%= active_link_to 'Проектирование', '/projects'%></li>
              </ul> -->
          <!--      <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Направления <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Промышленность</a></li>
                  <li><a href="#">Производсто</a></li>
                  <li><a href="#">Энергетика</a></li>
                  <li><a href="#">Наука</a></li>
                  <li><a href="#">Транспорт</a></li>
                  <li><a href="#">Инфраструктура</a></li>
                </ul>  -->
                <li><%= active_link_to 'Выполненные работы', '/projects'%></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Подрядчикам<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= active_link_to 'Закупка материалов', '/supply'%></li>
                    <li><%= active_link_to 'Субподрядные работы', '/work'%></li>
                  </ul>
                </li>
                <li><%= active_link_to 'Контакты', '/contacts'%></li>
              </ul>
          </div>
        </div>
      </div>
      </div>

    </nav>
  </div>
</div>