config/routes.rb
Rails.application.routes.draw do
  resources :vocations
  resources :works
  resources :supplies
  resources :users
  root 'static_pages#home'
  get '/home' => 'static_pages#home'
  get '/building' => 'static_pages#building'
  get '/projects' => 'static_pages#projects'
  get '/geo' => 'static_pages#geo'
  get '/about' => 'static_pages#about'
  get '/contacts' => 'static_pages#contacts'
  get '/hh' => 'static_pages#hh'
  get '/work' => 'static_pages#work'
  get '/supply' => 'static_pages#supply'
  resources :projects
  resources :sros

  namespace :admin do
    resources :projects
    resources :sros
    resources :vocations
    resources :works
    resources :supplies
    resources :users
    root 'projects#index'
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include Paperclip::Glue

  has_attached_file :photo, styles: { big: "1200x500>", medium: "1000x657>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  validates :photo, attachment_presence: true
  validates :title, :text, presence: true
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  def index
    @projects = Project.all
  end
  def new
    @project = Project.new
  end
  def edit
  @project = Project.find(params[:id])
  end
  def create
    @project = Project.new(model_params)
    if @project.save
      redirect_to admin_projects_path
    else
      render :new
    end
  end


  def show
    @project = Project.last
  end
  def update
    @project = Project.find(params[:id])
    if @project.update(model_params)
    redirect_to admin_project_path
    else
    render 'edit'
    end
  end
  def destroy
  @protect = Project.find(params[:id])
  @protect.destroy
  redirect_to admin_projects_path
  end
  private
  def model_params
    params.require(:project).permit(:title, :text, :photo)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
  end
end

app/views/admin/projects/edit.html.erb
<%= form_for [:admin, @project], html: { multipart: true } do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <%= form.text_area :text %>
  <%= form.file_field :photo %>
  <%= form.submit 'Сохранить', class: 'btn btn-default'%>
<% end %>

app/views/admin/projects/index.html.erb
<%= link_to 'Создать', new_admin_project_path, class: 'btn btn-default' %>

<table class="table">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Title</th>
      <th>Text</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td>
          <%= image_tag project.photo.url(:small) %>
        </td>
        <td>
          <%= project.title %>
        </td>
        <td>
          <%= project.text %>
        </td>
        <td>
          <%= link_to 'Редактировать', edit_admin_project_path(project), class: 'btn btn-default' %></td>
        </td>
        <td>
          <%= link_to 'Удалить', admin_project_path(project), class: 'btn btn-default',
          method: :delete,
          data: { confirm: 'Продолжить?' } %>
        </td>
    </tr>

    <% end %>
  </tbody>

app/views/admin/projects/new.html.erb
<%= form_for [:admin, @project], html: { multipart: true } do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <%= form.text_area :text %>
  <%= form.file_field :photo %>
  <%= form.submit 'Создать', class: 'btn btn-default'%>
<% end %>

app/views/admin/projects/show.html.erb
<%= image_tag @project.photo.url %>