config/routes.rb
Rails.application.routes.draw do
  resources :vocations
  resources :works
  resources :supplies
  resources :users
  root 'static_pages#home'
  get '/home' => 'static_pages#home'
  get '/building' => 'static_pages#building'
  get '/projects' => 'static_pages#projects'
  get '/geo' => 'static_pages#geo'
  get '/about' => 'static_pages#about'
  get '/contacts' => 'static_pages#contacts'
  get '/hh' => 'static_pages#hh'
  get '/work' => 'static_pages#work'
  get '/supply' => 'static_pages#supply'
  resources :projects
  resources :sros

  namespace :admin do
    resources :projects
    resources :sros
    resources :vocations
    resources :works
    resources :supplies
    resources :users
    root 'projects#index'
  end
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/admin/works_controller.rb
class Admin::WorksController < Admin::ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.fetch(:work, {})
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.fetch(:work, {})
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admin/works/_form.html.erb
<%= form_with(model: work, local: true) do |form| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/admin/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

app/views/admin/works/new.html.erb
<h1>New Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Back', works_path %>

app/views/admin/works/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>