config/routes.rb
Rails.application.routes.draw do
  resources :vocations
  resources :works
  resources :supplies
  resources :users
  root 'static_pages#home'
  get '/home' => 'static_pages#home'
  get '/building' => 'static_pages#building'
  get '/projects' => 'static_pages#projects'
  get '/geo' => 'static_pages#geo'
  get '/about' => 'static_pages#about'
  get '/contacts' => 'static_pages#contacts'
  get '/hh' => 'static_pages#hh'
  get '/work' => 'static_pages#work'
  get '/supply' => 'static_pages#supply'
  resources :projects
  resources :sros

  namespace :admin do
    resources :projects
    resources :sros
    resources :vocations
    resources :works
    resources :supplies
    resources :users
    root 'projects#index'
  end
end

app/models/supply.rb
class Supply < ApplicationRecord
end

app/controllers/admin/supplies_controller.rb
class Admin::SuppliesController < Admin::ApplicationController
  before_action :set_supply, only: [:show, :edit, :update, :destroy]

  # GET /supplies
  # GET /supplies.json
  def index
    @supplies = Supply.all
  end

  # GET /supplies/1
  # GET /supplies/1.json
  def show
  end

  # GET /supplies/new
  def new
    @supply = Supply.new
  end

  # GET /supplies/1/edit
  def edit
  end

  # POST /supplies
  # POST /supplies.json
  def create
    @supply = Supply.new(supply_params)

    respond_to do |format|
      if @supply.save
        format.html { redirect_to @supply, notice: 'Supply was successfully created.' }
        format.json { render :show, status: :created, location: @supply }
      else
        format.html { render :new }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplies/1
  # PATCH/PUT /supplies/1.json
  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to @supply, notice: 'Supply was successfully updated.' }
        format.json { render :show, status: :ok, location: @supply }
      else
        format.html { render :edit }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplies/1
  # DELETE /supplies/1.json
  def destroy
    @supply.destroy
    respond_to do |format|
      format.html { redirect_to supplies_url, notice: 'Supply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply
      @supply = Supply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supply_params
      params.fetch(:supply, {})
    end
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_action :set_supply, only: [:show, :edit, :update, :destroy]

  # GET /supplies
  # GET /supplies.json
  def index
    @supplies = Supply.all
  end

  # GET /supplies/1
  # GET /supplies/1.json
  def show
  end

  # GET /supplies/new
  def new
    @supply = Supply.new
  end

  # GET /supplies/1/edit
  def edit
  end

  # POST /supplies
  # POST /supplies.json
  def create
    @supply = Supply.new(supply_params)

    respond_to do |format|
      if @supply.save
        format.html { redirect_to @supply, notice: 'Supply was successfully created.' }
        format.json { render :show, status: :created, location: @supply }
      else
        format.html { render :new }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplies/1
  # PATCH/PUT /supplies/1.json
  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to @supply, notice: 'Supply was successfully updated.' }
        format.json { render :show, status: :ok, location: @supply }
      else
        format.html { render :edit }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplies/1
  # DELETE /supplies/1.json
  def destroy
    @supply.destroy
    respond_to do |format|
      format.html { redirect_to supplies_url, notice: 'Supply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply
      @supply = Supply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supply_params
      params.fetch(:supply, {})
    end
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/admin/supplies/_form.html.erb
<%= form_with(model: supply, local: true) do |form| %>
  <% if supply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(supply.errors.count, "error") %> prohibited this supply from being saved:</h2>

      <ul>
      <% supply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/supplies/edit.html.erb
<h1>Editing Supply</h1>

<%= render 'form', supply: @supply %>

<%= link_to 'Show', @supply %> |
<%= link_to 'Back', supplies_path %>

app/views/admin/supplies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Supplies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supplies.each do |supply| %>
      <tr>
        <td><%= link_to 'Show', supply %></td>
        <td><%= link_to 'Edit', edit_supply_path(supply) %></td>
        <td><%= link_to 'Destroy', supply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supply', new_supply_path %>

app/views/admin/supplies/new.html.erb
<h1>New Supply</h1>

<%= render 'form', supply: @supply %>

<%= link_to 'Back', supplies_path %>

app/views/admin/supplies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_supply_path(@supply) %> |
<%= link_to 'Back', supplies_path %>